// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserMFA = `-- name: DeleteUserMFA :exec
DELETE FROM user_mfa
WHERE user_id = $1
`

func (q *Queries) DeleteUserMFA(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserMFA, userID)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
       last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
FROM api_keys
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Prefix,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
       last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
FROM api_keys
WHERE prefix = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Prefix,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOAuthIdentityByProviderSubject = `-- name: GetOAuthIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_subject, email, linked_at, last_login_at, created_at, updated_at
FROM user_oauth_identities
WHERE provider = $1 AND provider_subject = $2
`

type GetOAuthIdentityByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetOAuthIdentityByProviderSubject(ctx context.Context, arg GetOAuthIdentityByProviderSubjectParams) (UserOauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i UserOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.LinkedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, status, created_at, updated_at, deleted_at
FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByName = `-- name: GetOrganizationByName :one
SELECT id, name, status, created_at, updated_at, deleted_at
FROM organizations
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByName(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByName, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, organization_id, email, full_name, is_active, is_platform_admin, password_hash,
       email_verified_at, password_changed_at, last_login_at, status,
       created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	IsPlatformAdmin   bool               `json:"is_platform_admin"`
	PasswordHash      *string            `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.IsPlatformAdmin,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, organization_id, email, full_name, is_active, is_platform_admin, password_hash,
       email_verified_at, password_changed_at, last_login_at, status,
       created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	IsPlatformAdmin   bool               `json:"is_platform_admin"`
	PasswordHash      *string            `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.IsPlatformAdmin,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserMFA = `-- name: GetUserMFA :one
SELECT user_id, totp_secret_encrypted, enabled_at, recovery_codes_hash, created_at, updated_at
FROM user_mfa
WHERE user_id = $1
`

func (q *Queries) GetUserMFA(ctx context.Context, userID uuid.UUID) (UserMfa, error) {
	row := q.db.QueryRow(ctx, getUserMFA, userID)
	var i UserMfa
	err := row.Scan(
		&i.UserID,
		&i.TotpSecretEncrypted,
		&i.EnabledAt,
		&i.RecoveryCodesHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, organization_id, name, environment, status, created_at, updated_at, deleted_at
FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceUser = `-- name: GetWorkspaceUser :one
SELECT workspace_id, user_id, role, created_at
FROM workspace_users
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceUser(ctx context.Context, arg GetWorkspaceUserParams) (WorkspaceUser, error) {
	row := q.db.QueryRow(ctx, getWorkspaceUser, arg.WorkspaceID, arg.UserID)
	var i WorkspaceUser
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (
  id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
  last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13
)
`

type InsertAPIKeyParams struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	Name              string             `json:"name"`
	KeyHash           string             `json:"key_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	Prefix            string             `json:"prefix"`
	LastUsedIp        *netip.Addr        `json:"last_used_ip"`
	LastUsedUserAgent *string            `json:"last_used_user_agent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyHash,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.Status,
		arg.Prefix,
		arg.LastUsedIp,
		arg.LastUsedUserAgent,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertOAuthIdentity = `-- name: InsertOAuthIdentity :exec
INSERT INTO user_oauth_identities (
  id, user_id, provider, provider_subject, email, linked_at, last_login_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertOAuthIdentityParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Email           string             `json:"email"`
	LinkedAt        pgtype.Timestamptz `json:"linked_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertOAuthIdentity(ctx context.Context, arg InsertOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, insertOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.LinkedAt,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertOrganization = `-- name: InsertOrganization :exec
INSERT INTO organizations (id, name, status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrganizationParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error {
	_, err := q.db.Exec(ctx, insertOrganization,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
  id, organization_id, email, full_name, is_active, is_platform_admin, password_hash,
  email_verified_at, password_changed_at, last_login_at, status,
  created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11,
  $12, $13, $14
)
`

type InsertUserParams struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	IsPlatformAdmin   bool               `json:"is_platform_admin"`
	PasswordHash      *string            `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.FullName,
		arg.IsActive,
		arg.IsPlatformAdmin,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.PasswordChangedAt,
		arg.LastLoginAt,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspaces (id, organization_id, name, environment, status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWorkspaceParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Environment    string             `json:"environment"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.Exec(ctx, insertWorkspace,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Environment,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertWorkspaceUser = `-- name: InsertWorkspaceUser :exec
INSERT INTO workspace_users (workspace_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertWorkspaceUserParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertWorkspaceUser(ctx context.Context, arg InsertWorkspaceUserParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceUser,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const listAPIKeysByWorkspace = `-- name: ListAPIKeysByWorkspace :many
SELECT id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
       last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
FROM api_keys
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Prefix,
			&i.LastUsedIp,
			&i.LastUsedUserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, status, created_at, updated_at, deleted_at
FROM organizations
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT id, organization_id, email, full_name, is_active, is_platform_admin, password_hash,
       email_verified_at, password_changed_at, last_login_at, status,
       created_at, updated_at, deleted_at
FROM users
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY email ASC
`

type ListUsersByOrganizationRow struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	IsPlatformAdmin   bool               `json:"is_platform_admin"`
	PasswordHash      *string            `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, organizationID uuid.UUID) ([]ListUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByOrganizationRow{}
	for rows.Next() {
		var i ListUsersByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.IsPlatformAdmin,
			&i.PasswordHash,
			&i.EmailVerifiedAt,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembersByWorkspace = `-- name: ListWorkspaceMembersByWorkspace :many
SELECT wu.workspace_id, wu.user_id, wu.role, wu.created_at,
       u.email, u.full_name
FROM workspace_users wu
INNER JOIN users u ON u.id = wu.user_id
WHERE wu.workspace_id = $1
ORDER BY wu.created_at ASC
`

type ListWorkspaceMembersByWorkspaceRow struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	FullName    string             `json:"full_name"`
}

func (q *Queries) ListWorkspaceMembersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersByWorkspaceRow{}
	for rows.Next() {
		var i ListWorkspaceMembersByWorkspaceRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceUsersByUser = `-- name: ListWorkspaceUsersByUser :many
SELECT workspace_id, user_id, role, created_at
FROM workspace_users
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaceUsersByUser(ctx context.Context, userID uuid.UUID) ([]WorkspaceUser, error) {
	rows, err := q.db.Query(ctx, listWorkspaceUsersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceUser{}
	for rows.Next() {
		var i WorkspaceUser
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceUsersByWorkspace = `-- name: ListWorkspaceUsersByWorkspace :many
SELECT workspace_id, user_id, role, created_at
FROM workspace_users
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaceUsersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceUser, error) {
	rows, err := q.db.Query(ctx, listWorkspaceUsersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceUser{}
	for rows.Next() {
		var i WorkspaceUser
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByOrganization = `-- name: ListWorkspacesByOrganization :many
SELECT id, organization_id, name, environment, status, created_at, updated_at, deleted_at
FROM workspaces
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspacesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Environment,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $2,
    updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type TouchAPIKeyLastUsedParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys
SET name = $2,
    key_hash = $3,
    expires_at = $4,
    status = $5,
    prefix = $6,
    updated_at = $7,
    deleted_at = $8
WHERE id = $1
`

type UpdateAPIKeyParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Status    string             `json:"status"`
	Prefix    string             `json:"prefix"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyHash,
		arg.ExpiresAt,
		arg.Status,
		arg.Prefix,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateOAuthIdentity = `-- name: UpdateOAuthIdentity :exec
UPDATE user_oauth_identities
SET email = $2,
    last_login_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateOAuthIdentityParams struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOAuthIdentity(ctx context.Context, arg UpdateOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, updateOAuthIdentity,
		arg.ID,
		arg.Email,
		arg.LastLoginAt,
		arg.UpdatedAt,
	)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = $2,
    status = $3,
    updated_at = $4,
    deleted_at = $5
WHERE id = $1
`

type UpdateOrganizationParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET full_name = $2,
    is_active = $3,
    password_hash = $4,
    email_verified_at = $5,
    password_changed_at = $6,
    last_login_at = $7,
    status = $8,
    updated_at = $9,
    deleted_at = $10
WHERE id = $1
`

type UpdateUserParams struct {
	ID                uuid.UUID          `json:"id"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	PasswordHash      *string            `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.IsActive,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.PasswordChangedAt,
		arg.LastLoginAt,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateUserMFA = `-- name: UpdateUserMFA :exec
UPDATE user_mfa
SET totp_secret_encrypted = $2,
    enabled_at = $3,
    recovery_codes_hash = $4,
    updated_at = $5
WHERE user_id = $1
`

type UpdateUserMFAParams struct {
	UserID              uuid.UUID          `json:"user_id"`
	TotpSecretEncrypted string             `json:"totp_secret_encrypted"`
	EnabledAt           pgtype.Timestamptz `json:"enabled_at"`
	RecoveryCodesHash   []byte             `json:"recovery_codes_hash"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserMFA(ctx context.Context, arg UpdateUserMFAParams) error {
	_, err := q.db.Exec(ctx, updateUserMFA,
		arg.UserID,
		arg.TotpSecretEncrypted,
		arg.EnabledAt,
		arg.RecoveryCodesHash,
		arg.UpdatedAt,
	)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces
SET name = $2,
    environment = $3,
    status = $4,
    updated_at = $5,
    deleted_at = $6
WHERE id = $1
`

type UpdateWorkspaceParams struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Environment string             `json:"environment"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.Exec(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Environment,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertUserMFA = `-- name: UpsertUserMFA :exec
INSERT INTO user_mfa (
  user_id, totp_secret_encrypted, enabled_at, recovery_codes_hash, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id) DO UPDATE
SET totp_secret_encrypted = EXCLUDED.totp_secret_encrypted,
    enabled_at = EXCLUDED.enabled_at,
    recovery_codes_hash = EXCLUDED.recovery_codes_hash,
    updated_at = EXCLUDED.updated_at
`

type UpsertUserMFAParams struct {
	UserID              uuid.UUID          `json:"user_id"`
	TotpSecretEncrypted string             `json:"totp_secret_encrypted"`
	EnabledAt           pgtype.Timestamptz `json:"enabled_at"`
	RecoveryCodesHash   []byte             `json:"recovery_codes_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserMFA(ctx context.Context, arg UpsertUserMFAParams) error {
	_, err := q.db.Exec(ctx, upsertUserMFA,
		arg.UserID,
		arg.TotpSecretEncrypted,
		arg.EnabledAt,
		arg.RecoveryCodesHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
