// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	Name              string             `json:"name"`
	KeyHash           string             `json:"key_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	Prefix            string             `json:"prefix"`
	LastUsedIp        *netip.Addr        `json:"last_used_ip"`
	LastUsedUserAgent *string            `json:"last_used_user_agent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ActorType      string             `json:"actor_type"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	RequestID      *string            `json:"request_id"`
	CorrelationID  *string            `json:"correlation_id"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      *string            `json:"user_agent"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Connection struct {
	ID                 uuid.UUID          `json:"id"`
	ActiveCredentialID pgtype.UUID        `json:"active_credential_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ConnectorID        uuid.UUID          `json:"connector_id"`
	Name               string             `json:"name"`
	IsDefault          bool               `json:"is_default"`
	Description        *string            `json:"description"`
	Environment        string             `json:"environment"`
	Status             string             `json:"status"`
	Config             []byte             `json:"config"`
	RetryPolicy        []byte             `json:"retry_policy"`
	TimeoutSeconds     int32              `json:"timeout_seconds"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Connector struct {
	ID               uuid.UUID          `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Vendor           string             `json:"vendor"`
	Category         string             `json:"category"`
	Version          string             `json:"version"`
	Status           string             `json:"status"`
	Description      *string            `json:"description"`
	Homepage         *string            `json:"homepage"`
	DocumentationUrl *string            `json:"documentation_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ConnectorCapability struct {
	ID             uuid.UUID          `json:"id"`
	ConnectorID    uuid.UUID          `json:"connector_id"`
	CapabilityCode string             `json:"capability_code"`
	DisplayName    string             `json:"display_name"`
	Status         string             `json:"status"`
	IsAsync        bool               `json:"is_async"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Credential struct {
	ID              uuid.UUID          `json:"id"`
	ConnectionID    uuid.UUID          `json:"connection_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	Version         int32              `json:"version"`
	EncryptedSecret []byte             `json:"encrypted_secret"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RotatedAt       pgtype.Timestamptz `json:"rotated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
}

type Event struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	AggregateType  string             `json:"aggregate_type"`
	AggregateID    uuid.UUID          `json:"aggregate_id"`
	ExecutionID    pgtype.UUID        `json:"execution_id"`
	Category       string             `json:"category"`
	EventName      string             `json:"event_name"`
	CorrelationID  *string            `json:"correlation_id"`
	Payload        []byte             `json:"payload"`
	Metadata       []byte             `json:"metadata"`
	PublishedBy    *string            `json:"published_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Execution struct {
	ID            uuid.UUID          `json:"id"`
	IntentID      uuid.UUID          `json:"intent_id"`
	Status        string             `json:"status"`
	Result        interface{}        `json:"result"`
	RetryAttempt  int32              `json:"retry_attempt"`
	CurrentStepNo int32              `json:"current_step_no"`
	Context       []byte             `json:"context"`
	FailureReason *string            `json:"failure_reason"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ExecutionSnapshot struct {
	ID           uuid.UUID          `json:"id"`
	ExecutionID  uuid.UUID          `json:"execution_id"`
	StepID       pgtype.UUID        `json:"step_id"`
	SnapshotType string             `json:"snapshot_type"`
	Snapshot     []byte             `json:"snapshot"`
	ContentType  *string            `json:"content_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ExecutionStep struct {
	ID           uuid.UUID          `json:"id"`
	ExecutionID  uuid.UUID          `json:"execution_id"`
	StepNo       int32              `json:"step_no"`
	StepType     string             `json:"step_type"`
	Status       string             `json:"status"`
	RetryAttempt int32              `json:"retry_attempt"`
	DurationMs   *int32             `json:"duration_ms"`
	ErrorMessage *string            `json:"error_message"`
	ErrorCode    *string            `json:"error_code"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type ExecutionTimeline struct {
	ID          uuid.UUID          `json:"id"`
	ExecutionID uuid.UUID          `json:"execution_id"`
	Event       string             `json:"event"`
	Message     *string            `json:"message"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	IntentID       pgtype.UUID        `json:"intent_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Intent struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	ConnectionID   uuid.UUID          `json:"connection_id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	CorrelationID  *string            `json:"correlation_id"`
	IdempotencyKey *string            `json:"idempotency_key"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type SyncRoute struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	SourceConnectionID uuid.UUID          `json:"source_connection_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	TriggerType        string             `json:"trigger_type"`
	ResourceTypes      []byte             `json:"resource_types"`
	Schedule           []byte             `json:"schedule"`
	Filter             []byte             `json:"filter"`
	IdempotencyRule    []byte             `json:"idempotency_rule"`
	Activities         []byte             `json:"activities"`
	Reverse            []byte             `json:"reverse"`
	RetryPolicy        []byte             `json:"retry_policy"`
	WebhookSecret      []byte             `json:"webhook_secret"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type SyncRouteWatermark struct {
	SyncRouteID  uuid.UUID          `json:"sync_route_id"`
	ResourceType string             `json:"resource_type"`
	Cursor       []byte             `json:"cursor"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	PasswordHash      string             `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Workspace struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Environment    string             `json:"environment"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceUser struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
