// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestration.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, intent_id, status, result, retry_attempt, current_step_no, context,
       failure_reason, started_at, completed_at, created_at
FROM executions
WHERE id = $1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id uuid.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Status,
		&i.Result,
		&i.RetryAttempt,
		&i.CurrentStepNo,
		&i.Context,
		&i.FailureReason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionByIntentID = `-- name: GetExecutionByIntentID :one
SELECT id, intent_id, status, result, retry_attempt, current_step_no, context,
       failure_reason, started_at, completed_at, created_at
FROM executions
WHERE intent_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetExecutionByIntentID(ctx context.Context, intentID uuid.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByIntentID, intentID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Status,
		&i.Result,
		&i.RetryAttempt,
		&i.CurrentStepNo,
		&i.Context,
		&i.FailureReason,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKeyByOrgWorkspaceKey = `-- name: GetIdempotencyKeyByOrgWorkspaceKey :one
SELECT id, organization_id, workspace_id, idempotency_key, intent_id, expires_at, created_at
FROM idempotency_keys
WHERE organization_id = $1 AND workspace_id = $2 AND idempotency_key = $3
`

type GetIdempotencyKeyByOrgWorkspaceKeyParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	WorkspaceID    uuid.UUID `json:"workspace_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyKeyByOrgWorkspaceKey(ctx context.Context, arg GetIdempotencyKeyByOrgWorkspaceKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyByOrgWorkspaceKey, arg.OrganizationID, arg.WorkspaceID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.IdempotencyKey,
		&i.IntentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIntentByID = `-- name: GetIntentByID :one
SELECT id, organization_id, workspace_id, connection_id, capability, payload,
       status, correlation_id, idempotency_key, submitted_at, created_at
FROM intents
WHERE id = $1
`

func (q *Queries) GetIntentByID(ctx context.Context, id uuid.UUID) (Intent, error) {
	row := q.db.QueryRow(ctx, getIntentByID, id)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.WorkspaceID,
		&i.ConnectionID,
		&i.Capability,
		&i.Payload,
		&i.Status,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.SubmittedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertExecution = `-- name: InsertExecution :exec
INSERT INTO executions (
  id, intent_id, status, result, retry_attempt, current_step_no, context,
  failure_reason, started_at, completed_at, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11
)
`

type InsertExecutionParams struct {
	ID            uuid.UUID          `json:"id"`
	IntentID      uuid.UUID          `json:"intent_id"`
	Status        string             `json:"status"`
	Result        interface{}        `json:"result"`
	RetryAttempt  int32              `json:"retry_attempt"`
	CurrentStepNo int32              `json:"current_step_no"`
	Context       []byte             `json:"context"`
	FailureReason *string            `json:"failure_reason"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertExecution(ctx context.Context, arg InsertExecutionParams) error {
	_, err := q.db.Exec(ctx, insertExecution,
		arg.ID,
		arg.IntentID,
		arg.Status,
		arg.Result,
		arg.RetryAttempt,
		arg.CurrentStepNo,
		arg.Context,
		arg.FailureReason,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CreatedAt,
	)
	return err
}

const insertExecutionSnapshot = `-- name: InsertExecutionSnapshot :exec
INSERT INTO execution_snapshots (
  id, execution_id, step_id, snapshot_type, snapshot, content_type, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO NOTHING
`

type InsertExecutionSnapshotParams struct {
	ID           uuid.UUID          `json:"id"`
	ExecutionID  uuid.UUID          `json:"execution_id"`
	StepID       pgtype.UUID        `json:"step_id"`
	SnapshotType string             `json:"snapshot_type"`
	Snapshot     []byte             `json:"snapshot"`
	ContentType  *string            `json:"content_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertExecutionSnapshot(ctx context.Context, arg InsertExecutionSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertExecutionSnapshot,
		arg.ID,
		arg.ExecutionID,
		arg.StepID,
		arg.SnapshotType,
		arg.Snapshot,
		arg.ContentType,
		arg.CreatedAt,
	)
	return err
}

const insertExecutionStep = `-- name: InsertExecutionStep :exec
INSERT INTO execution_steps (
  id, execution_id, step_no, step_type, status, retry_attempt, duration_ms,
  error_message, error_code, started_at, completed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11
)
`

type InsertExecutionStepParams struct {
	ID           uuid.UUID          `json:"id"`
	ExecutionID  uuid.UUID          `json:"execution_id"`
	StepNo       int32              `json:"step_no"`
	StepType     string             `json:"step_type"`
	Status       string             `json:"status"`
	RetryAttempt int32              `json:"retry_attempt"`
	DurationMs   *int32             `json:"duration_ms"`
	ErrorMessage *string            `json:"error_message"`
	ErrorCode    *string            `json:"error_code"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) InsertExecutionStep(ctx context.Context, arg InsertExecutionStepParams) error {
	_, err := q.db.Exec(ctx, insertExecutionStep,
		arg.ID,
		arg.ExecutionID,
		arg.StepNo,
		arg.StepType,
		arg.Status,
		arg.RetryAttempt,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.ErrorCode,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const insertExecutionTimeline = `-- name: InsertExecutionTimeline :exec
INSERT INTO execution_timelines (
  id, execution_id, event, message, metadata, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id) DO NOTHING
`

type InsertExecutionTimelineParams struct {
	ID          uuid.UUID          `json:"id"`
	ExecutionID uuid.UUID          `json:"execution_id"`
	Event       string             `json:"event"`
	Message     *string            `json:"message"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertExecutionTimeline(ctx context.Context, arg InsertExecutionTimelineParams) error {
	_, err := q.db.Exec(ctx, insertExecutionTimeline,
		arg.ID,
		arg.ExecutionID,
		arg.Event,
		arg.Message,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (
  id, organization_id, workspace_id, idempotency_key, intent_id, expires_at, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertIdempotencyKeyParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	IntentID       pgtype.UUID        `json:"intent_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.ID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.IntentID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertIntent = `-- name: InsertIntent :exec
INSERT INTO intents (
  id, organization_id, workspace_id, connection_id, capability, payload,
  status, correlation_id, idempotency_key, submitted_at, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11
)
`

type InsertIntentParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	ConnectionID   uuid.UUID          `json:"connection_id"`
	Capability     string             `json:"capability"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	CorrelationID  *string            `json:"correlation_id"`
	IdempotencyKey *string            `json:"idempotency_key"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertIntent(ctx context.Context, arg InsertIntentParams) error {
	_, err := q.db.Exec(ctx, insertIntent,
		arg.ID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.ConnectionID,
		arg.Capability,
		arg.Payload,
		arg.Status,
		arg.CorrelationID,
		arg.IdempotencyKey,
		arg.SubmittedAt,
		arg.CreatedAt,
	)
	return err
}

const listExecutionSnapshotsByExecution = `-- name: ListExecutionSnapshotsByExecution :many
SELECT id, execution_id, step_id, snapshot_type, snapshot, content_type, created_at
FROM execution_snapshots
WHERE execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListExecutionSnapshotsByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionSnapshot, error) {
	rows, err := q.db.Query(ctx, listExecutionSnapshotsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionSnapshot{}
	for rows.Next() {
		var i ExecutionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.StepID,
			&i.SnapshotType,
			&i.Snapshot,
			&i.ContentType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionStepsByExecution = `-- name: ListExecutionStepsByExecution :many
SELECT id, execution_id, step_no, step_type, status, retry_attempt, duration_ms,
       error_message, error_code, started_at, completed_at
FROM execution_steps
WHERE execution_id = $1
ORDER BY step_no ASC
`

func (q *Queries) ListExecutionStepsByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionStep, error) {
	rows, err := q.db.Query(ctx, listExecutionStepsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionStep{}
	for rows.Next() {
		var i ExecutionStep
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.StepNo,
			&i.StepType,
			&i.Status,
			&i.RetryAttempt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.ErrorCode,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionTimelinesByExecution = `-- name: ListExecutionTimelinesByExecution :many
SELECT id, execution_id, event, message, metadata, created_at
FROM execution_timelines
WHERE execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListExecutionTimelinesByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionTimeline, error) {
	rows, err := q.db.Query(ctx, listExecutionTimelinesByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionTimeline{}
	for rows.Next() {
		var i ExecutionTimeline
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.Event,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByIntentID = `-- name: ListExecutionsByIntentID :many
SELECT id, intent_id, status, result, retry_attempt, current_step_no, context,
       failure_reason, started_at, completed_at, created_at
FROM executions
WHERE intent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListExecutionsByIntentID(ctx context.Context, intentID uuid.UUID) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutionsByIntentID, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.Status,
			&i.Result,
			&i.RetryAttempt,
			&i.CurrentStepNo,
			&i.Context,
			&i.FailureReason,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecution = `-- name: UpdateExecution :exec
UPDATE executions
SET status = $2,
    result = $3,
    retry_attempt = $4,
    current_step_no = $5,
    context = $6,
    failure_reason = $7,
    started_at = $8,
    completed_at = $9
WHERE id = $1
`

type UpdateExecutionParams struct {
	ID            uuid.UUID          `json:"id"`
	Status        string             `json:"status"`
	Result        interface{}        `json:"result"`
	RetryAttempt  int32              `json:"retry_attempt"`
	CurrentStepNo int32              `json:"current_step_no"`
	Context       []byte             `json:"context"`
	FailureReason *string            `json:"failure_reason"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateExecution(ctx context.Context, arg UpdateExecutionParams) error {
	_, err := q.db.Exec(ctx, updateExecution,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.RetryAttempt,
		arg.CurrentStepNo,
		arg.Context,
		arg.FailureReason,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const updateExecutionStep = `-- name: UpdateExecutionStep :exec
UPDATE execution_steps
SET status = $2,
    retry_attempt = $3,
    duration_ms = $4,
    error_message = $5,
    error_code = $6,
    started_at = $7,
    completed_at = $8
WHERE id = $1
`

type UpdateExecutionStepParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	RetryAttempt int32              `json:"retry_attempt"`
	DurationMs   *int32             `json:"duration_ms"`
	ErrorMessage *string            `json:"error_message"`
	ErrorCode    *string            `json:"error_code"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateExecutionStep(ctx context.Context, arg UpdateExecutionStepParams) error {
	_, err := q.db.Exec(ctx, updateExecutionStep,
		arg.ID,
		arg.Status,
		arg.RetryAttempt,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.ErrorCode,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const updateIntent = `-- name: UpdateIntent :exec
UPDATE intents
SET status = $2
WHERE id = $1
`

type UpdateIntentParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateIntent(ctx context.Context, arg UpdateIntentParams) error {
	_, err := q.db.Exec(ctx, updateIntent, arg.ID, arg.Status)
	return err
}
