/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register organization + owner + default workspace */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and issue JWT + refresh token */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh token */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get organization */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/organizations/{organizationId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend organization */
        post: operations["suspendOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/organizations/{organizationId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate suspended organization */
        post: operations["activateOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/organizations/{organizationId}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces */
        get: operations["listWorkspaces"];
        put?: never;
        /** Create workspace */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/workspaces/{workspaceId}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable workspace */
        post: operations["enableWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/workspaces/{workspaceId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable workspace */
        post: operations["disableWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add user to workspace */
        post: operations["addWorkspaceMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/workspaces/{workspaceId}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys */
        get: operations["listAPIKeys"];
        put?: never;
        /** Create API key (plaintext returned once) */
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/workspaces/{workspaceId}/api-keys/{apiKeyId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable API key */
        post: operations["disableAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/workspaces/{workspaceId}/api-keys/{apiKeyId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate API key (new plaintext once) */
        post: operations["rotateAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connectors */
        get: operations["listConnectors"];
        put?: never;
        /** Register a Connector (platform admin / seed) */
        post: operations["registerConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/connectors/{connectorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connector */
        get: operations["getConnector"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/connectors/{connectorId}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Connector */
        post: operations["enableConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/connectors/{connectorId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Connector */
        post: operations["disableConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/connectors/{connectorId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove Connector (terminal) */
        post: operations["removeConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections in a Workspace */
        get: operations["listConnections"];
        put?: never;
        /** Create Connection (Draft) with initial Credential */
        post: operations["createConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/connections/{connectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["getConnection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/connections/{connectionId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Connection (Draft/VerificationFailed -> Verifying -> Active|VerificationFailed) */
        post: operations["verifyConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/connections/{connectionId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Connection */
        post: operations["disableConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/connections/{connectionId}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Connection (must have been previously verified) */
        post: operations["enableConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/connections/{connectionId}/credentials/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Credential (revokes previous, never returns secret) */
        post: operations["rotateCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SyncRoutes in a Workspace */
        get: operations["listSyncRoutes"];
        put?: never;
        /**
         * Create SyncRoute (Draft)
         * @description Workspace-scoped origin → destination fan-out configuration (not a Workflow).
         *     When trigger_type is webhook|both, generates a webhook secret; plaintext is returned
         *     once in the response as webhook_secret and never again (use rotate to re-issue).
         */
        post: operations["createSyncRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes/{syncRouteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get SyncRoute */
        get: operations["getSyncRoute"];
        put?: never;
        post?: never;
        /** Soft-delete SyncRoute (must not be Enabled) */
        delete: operations["deleteSyncRoute"];
        options?: never;
        head?: never;
        /** Update SyncRoute (Draft or Disabled only) */
        patch: operations["updateSyncRoute"];
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes/{syncRouteId}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable SyncRoute */
        post: operations["enableSyncRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes/{syncRouteId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable SyncRoute */
        post: operations["disableSyncRoute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes/{syncRouteId}/webhook-secret/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate SyncRoute webhook secret (plaintext once) */
        post: operations["rotateSyncRouteWebhookSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes/{syncRouteId}/watermarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List poll watermarks for a SyncRoute */
        get: operations["listSyncRouteWatermarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration/workspaces/{workspaceId}/sync-routes/{syncRouteId}/watermarks/{resourceType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert poll watermark cursor */
        put: operations["upsertSyncRouteWatermark"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/sync-routes/{syncRouteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inbound SyncRoute webhook (shared-secret header)
         * @description Public ingress (no JWT / API key). Validates `X-Hublio-Webhook-Secret` against the
         *     SyncRoute encrypted secret (constant-time), checks Enabled + webhook|both trigger,
         *     resource_type allow-list, and optional JSON filter. On success submits a Business
         *     Intent bound to the SyncRoute source Connection and fans out to one Execution per
         *     activity step (sequential or parallel per group; optional reverse). Response includes
         *     `execution_id` (first) and `execution_ids` (all). Idempotency key may be supplied or
         *     is derived from workspace + route + resource + operation + business key. Never logs
         *     the webhook secret.
         */
        post: operations["acceptSyncRouteWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync-routes/{syncRouteId}/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run SyncRoute poll tick (watermark + list + Intent fan-out)
         * @description API Key ops/smoke endpoint. Pulls from the SyncRoute source Connection via list
         *     capability (default `invoice.list`) using the Postgres watermark cursor, filters
         *     each record, submits Intents with fan-out, then advances the watermark after a
         *     successful pull cycle (docs/30 §7.2). The worker also ticks Enabled schedule|both
         *     routes on `POLL_TICK_INTERVAL_SECONDS` (default 30s) via `integration.poll_sync_route`
         *     jobs. Destination Execution failures do not roll back the watermark.
         */
        post: operations["triggerSyncRoutePoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a Business Intent (Workspace-scoped, API Key)
         * @description Resolves the Connection (must be Active), creates the Intent (Submitted), then
         *     Accepts or Rejects it based on payload/capability validity. On Accept, creates and
         *     Queues one Execution (direct submit) and enqueues the `orchestration.execution`
         *     worker job. SyncRoute webhook ingress may fan out to multiple Executions under the
         *     same Intent. Idempotency-Key is required; replays return the original Intent/Execution(s).
         */
        post: operations["submitIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intent (tenant-scoped) */
        get: operations["getIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution (with Steps/Timeline; tenant-scoped) */
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{executionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a Queued/Running Execution (terminal) */
        post: operations["cancelExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{executionId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually retry a Failed Execution (Failed -> Queued)
         * @description Replay (new Execution for the same Intent) is deferred in v1: executions.intent_id is
         *     UNIQUE, so retry re-runs the same Execution row instead of creating a new one.
         */
        post: operations["retryExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{executionId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Execution timeline (Observability, F3; tenant-scoped)
         * @description Focused view of the same execution_timelines rows already returned inline by
         *     GET /api/v1/executions/{executionId}.
         */
        get: operations["getExecutionTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List persisted Platform Events (Observability, F3; Workspace-scoped)
         * @description Append-only PlatformEvent facts (`events` table) published after a successful
         *     Identity/Integration/Orchestration commit. Never used to schedule work (Event
         *     Platform is not a work queue).
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Machine health (API key) */
        get: operations["machineHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/queue/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue platform.health job */
        post: operations["enqueuePlatformHealth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observability counters (Phase F, JSON; API key)
         * @description In-memory, per-process counters: executions_succeeded_total, executions_failed_total,
         *     events_published_total, audit_records_total, plus best-effort queue_depth (Redis LLEN).
         *     Same payload as GET /metrics (unauthenticated) for scrapers that expect that path.
         */
        get: operations["platformMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observability counters (Phase F, JSON; unauthenticated) */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @example success */
            status?: string;
            message?: string;
            /** @description Payload varies by endpoint */
            data?: unknown;
        };
        ErrorEnvelope: {
            error?: string;
            /** @example BAD_REQUEST */
            code?: string;
            detail?: string;
        };
        RegisterRequest: {
            organization_name: string;
            /** Format: email */
            email: string;
            password: string;
            full_name: string;
            /** @default default */
            workspace_name: string;
            /** @default production */
            environment: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterConnectorRequest: {
            /**
             * @description Built-in codes include fake, misa, nhanh (seeded on API boot).
             * @example misa
             */
            code: string;
            name: string;
            vendor: string;
            /** @enum {string} */
            category: "source" | "destination" | "bidirectional" | "utility";
            /** @example 1.0.0 */
            version: string;
            description?: string;
            homepage?: string;
            documentation_url?: string;
            capabilities?: {
                /** @example invoice.create */
                code: string;
                display_name: string;
                /** @default false */
                is_async: boolean;
            }[];
        };
        CreateConnectionRequest: {
            /** Format: uuid */
            connector_id: string;
            name: string;
            /** @default false */
            is_default: boolean;
            description?: string;
            /** @example sandbox */
            environment: string;
            /**
             * @description Provider-agnostic Connection config (JSONB). Examples:
             *     MISA — tax_code, inv_series, optional base_url (default testapi.meinvoice.vn/api/integration),
             *     optional sign_type (default 2);
             *     Nhanh — app_id, business_id, optional base_url (default pos.open.nhanh.vn/v3.0).
             * @example {
             *       "tax_code": "0101243150",
             *       "inv_series": "1C25TYY",
             *       "base_url": "https://testapi.meinvoice.vn/api/integration"
             *     }
             */
            config?: Record<string, never>;
            retry_policy?: Record<string, never>;
            /** @default 30 */
            timeout_seconds: number;
            /** @enum {string} */
            credential_type: "api_key" | "oauth2" | "bearer_token" | "basic_auth" | "jwt";
            /**
             * @description Plaintext credential fields; encrypted at rest, never echoed back.
             *     MISA — app_id, username, password (tax_code may live here or in config);
             *     Nhanh — access_token.
             * @example {
             *       "app_id": "your-misa-app-id",
             *       "username": "user@example.com",
             *       "password": "********"
             *     }
             */
            secret: Record<string, never>;
            /** Format: date-time */
            credential_expires_at?: string;
        };
        SubmitIntentRequest: {
            /** Format: uuid */
            connection_id: string;
            /**
             * @description Must match a capability on the Connection's Connector.
             *     MISA — invoice.create; Nhanh — invoice.get, invoice.update_status; Fake — echo.
             * @example invoice.create
             */
            capability: string;
            /**
             * @description Canonical-ish business payload (JSONB). For MISA invoice.create include at least
             *     invoice_number, issue_date, customer.name, and items[].
             * @example {
             *       "invoice_number": "INV-100",
             *       "issue_date": "2026-07-15T10:00:00Z",
             *       "currency": "VND",
             *       "customer": {
             *         "name": "Cong ty ABC",
             *         "tax_code": "0300000000"
             *       },
             *       "items": [
             *         {
             *           "code": "SKU-1",
             *           "name": "San pham 1",
             *           "quantity": 2,
             *           "unit_price": 100000,
             *           "vat_rate": "10%"
             *         }
             *       ],
             *       "subtotal": 200000,
             *       "total": 220000
             *     }
             */
            payload?: Record<string, never>;
            /** @description Defaults to the request's correlation id when omitted */
            correlation_id?: string;
        };
        RotateCredentialRequest: {
            /** @enum {string} */
            credential_type: "api_key" | "oauth2" | "bearer_token" | "basic_auth" | "jwt";
            /** @description Plaintext credential fields; encrypted at rest, never echoed back */
            secret: Record<string, never>;
            /** Format: date-time */
            expires_at?: string;
        };
        CreateSyncRouteRequest: {
            /** Format: uuid */
            source_connection_id: string;
            /** @example Nhanh to MISA invoices */
            name: string;
            /** @enum {string} */
            trigger_type: "webhook" | "schedule" | "both";
            /**
             * @example [
             *       "invoice"
             *     ]
             */
            resource_types: string[];
            /**
             * @description Required when trigger_type is schedule|both. MVP key: interval_seconds (1..86400).
             *     Optional list_capability overrides the source pull capability (default invoice.list).
             * @example {
             *       "interval_seconds": 300,
             *       "list_capability": "invoice.list"
             *     }
             */
            schedule?: Record<string, never>;
            /** @description JSON condition tree (AND/OR); not a Rule Engine */
            filter?: Record<string, never>;
            /**
             * @example {
             *       "rule": "provider_triple"
             *     }
             */
            idempotency_rule?: Record<string, never>;
            activities: components["schemas"]["SyncRouteActivityGroup"][];
            reverse?: components["schemas"]["SyncRouteReverse"];
            retry_policy?: Record<string, never>;
        };
        UpdateSyncRouteRequest: {
            name?: string;
            /** Format: uuid */
            source_connection_id?: string;
            /** @enum {string} */
            trigger_type?: "webhook" | "schedule" | "both";
            resource_types?: string[];
            schedule?: Record<string, never>;
            filter?: Record<string, never>;
            idempotency_rule?: Record<string, never>;
            activities?: components["schemas"]["SyncRouteActivityGroup"][];
            reverse?: components["schemas"]["SyncRouteReverse"];
            /** @default false */
            clear_reverse: boolean;
            retry_policy?: Record<string, never>;
        };
        SyncRouteActivityGroup: {
            /** @enum {string} */
            group_mode: "sequential" | "parallel";
            steps: {
                /** Format: uuid */
                destination_connection_id: string;
                /** @example invoice.create */
                capability: string;
                mapping_key?: string;
            }[];
        };
        SyncRouteReverse: {
            /** @example invoice.update_status */
            capability: string;
            /**
             * @default success
             * @enum {string}
             */
            on: "success" | "failure" | "always";
        };
        AcceptWebhookRequest: {
            /** @example invoice */
            resource_type: string;
            /**
             * @description Defaults to upsert; used in derived idempotency key
             * @example create
             */
            operation?: string;
            /**
             * @description Canonical-ish business payload for the Intent
             * @example {
             *       "invoice_number": "INV-100",
             *       "issue_date": "2026-07-15T10:00:00Z",
             *       "currency": "VND",
             *       "customer": {
             *         "name": "Cong ty ABC"
             *       },
             *       "items": [
             *         {
             *           "name": "San pham 1",
             *           "quantity": 1,
             *           "unit_price": 100000
             *         }
             *       ]
             *     }
             */
            payload: {
                [key: string]: unknown;
            };
            /** @description Optional; when omitted Hublio derives a stable key */
            idempotency_key?: string;
            correlation_id?: string;
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        organizationId: string;
        workspaceId: string;
        apiKeyId: string;
        connectorId: string;
        connectionId: string;
        syncRouteId: string;
        intentId: string;
        executionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example hublio-api */
                        service?: string;
                    };
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Degraded (Postgres/Redis) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    suspendOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suspended */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    activateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["organizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @example production */
                    environment: string;
                };
            };
        };
        responses: {
            /** @description Workspace created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enableWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disableWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addWorkspaceMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    /** @enum {string} */
                    role: "owner" | "admin" | "member";
                };
            };
        };
        responses: {
            /** @description Member added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API keys (never includes plaintext) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created; includes plaintext once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    disableAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                apiKeyId: components["parameters"]["apiKeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rotateAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                apiKeyId: components["parameters"]["apiKeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterConnectorRequest"];
            };
        };
        responses: {
            /** @description Connector registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    getConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["connectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connector */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    enableConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["connectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    disableConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["connectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    removeConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: components["parameters"]["connectorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    createConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionRequest"];
            };
        };
        responses: {
            /** @description Connection created; credential never includes plaintext/ciphertext */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                connectionId: components["parameters"]["connectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    verifyConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                connectionId: components["parameters"]["connectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification finished (inspect status; active or verification_failed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    disableConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                connectionId: components["parameters"]["connectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    enableConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                connectionId: components["parameters"]["connectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    rotateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                connectionId: components["parameters"]["connectionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateCredentialRequest"];
            };
        };
        responses: {
            /** @description Rotated; response never includes plaintext or ciphertext */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listSyncRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SyncRoute list (webhook_secret never included) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createSyncRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSyncRouteRequest"];
            };
        };
        responses: {
            /** @description Created (may include webhook_secret once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    getSyncRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SyncRoute (has_webhook_secret flag; no plaintext) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    deleteSyncRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    updateSyncRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSyncRouteRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    enableSyncRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    disableSyncRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    rotateSyncRouteWebhookSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rotated; response includes webhook_secret once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    listSyncRouteWatermarks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Watermark list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsertSyncRouteWatermark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["workspaceId"];
                syncRouteId: components["parameters"]["syncRouteId"];
                resourceType: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example {
                     *       "last_updated_at": "2026-07-19T00:00:00Z",
                     *       "last_record_id": "123"
                     *     }
                     */
                    cursor: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptSyncRouteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptWebhookRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Intent created (or accepted) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    triggerSyncRoutePoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syncRouteId: components["parameters"]["syncRouteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example invoice */
                    resource_type: string;
                };
            };
        };
        responses: {
            /** @description Poll completed (may accept zero records) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    submitIntent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIntentRequest"];
            };
        };
        responses: {
            /** @description Idempotency-Key replay of a previously submitted Intent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Intent submitted (created) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intentId: components["parameters"]["intentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["executionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    cancelExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["executionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    retryExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["executionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retry scheduled (re-enqueued) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getExecutionTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["executionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Execution timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                execution_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    machineHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    enqueuePlatformHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    platformMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
