#  ================= STAGE 1: BUILD GO BINARY =================
FROM golang:1.25.5-alpine3.22 AS builder

RUN apk update && apk add --no-cache git curl
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY . .

CMD ["air", "-c", ".air.worker.toml"]