#  ================= STAGE 1: BUILD GO BINARY =================
FROM golang:1.25.5-alpine3.22 AS builder

RUN apk update && apk add --no-cache git curl

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build -o main ./cmd/api

#  ================= STAGE 2: RUNTIME CONTAINER =================
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/main .
COPY .env .

EXPOSE 8080

CMD ["./main"]