// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
  id, organization_id, workspace_id, actor_type, actor_id, action, resource_type,
  resource_id, request_id, correlation_id, ip, user_agent, metadata, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13, $14
)
`

type InsertAuditLogParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ActorType      string             `json:"actor_type"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	Action         string             `json:"action"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     pgtype.UUID        `json:"resource_id"`
	RequestID      *string            `json:"request_id"`
	CorrelationID  *string            `json:"correlation_id"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      *string            `json:"user_agent"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.CorrelationID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
  id, organization_id, workspace_id, aggregate_type, aggregate_id, execution_id,
  category, event_name, correlation_id, payload, metadata, published_by, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12, $13
)
`

type InsertEventParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	AggregateType  string             `json:"aggregate_type"`
	AggregateID    uuid.UUID          `json:"aggregate_id"`
	ExecutionID    pgtype.UUID        `json:"execution_id"`
	Category       string             `json:"category"`
	EventName      string             `json:"event_name"`
	CorrelationID  *string            `json:"correlation_id"`
	Payload        []byte             `json:"payload"`
	Metadata       []byte             `json:"metadata"`
	PublishedBy    *string            `json:"published_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.OrganizationID,
		arg.WorkspaceID,
		arg.AggregateType,
		arg.AggregateID,
		arg.ExecutionID,
		arg.Category,
		arg.EventName,
		arg.CorrelationID,
		arg.Payload,
		arg.Metadata,
		arg.PublishedBy,
		arg.CreatedAt,
	)
	return err
}

const listEventsByWorkspace = `-- name: ListEventsByWorkspace :many
SELECT id, organization_id, workspace_id, aggregate_type, aggregate_id, execution_id,
       category, event_name, correlation_id, payload, metadata, published_by, created_at
FROM events
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListEventsByWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListEventsByWorkspace(ctx context.Context, arg ListEventsByWorkspaceParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.ExecutionID,
			&i.Category,
			&i.EventName,
			&i.CorrelationID,
			&i.Payload,
			&i.Metadata,
			&i.PublishedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByWorkspaceAndExecution = `-- name: ListEventsByWorkspaceAndExecution :many
SELECT id, organization_id, workspace_id, aggregate_type, aggregate_id, execution_id,
       category, event_name, correlation_id, payload, metadata, published_by, created_at
FROM events
WHERE workspace_id = $1 AND execution_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListEventsByWorkspaceAndExecutionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ExecutionID pgtype.UUID `json:"execution_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListEventsByWorkspaceAndExecution(ctx context.Context, arg ListEventsByWorkspaceAndExecutionParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByWorkspaceAndExecution, arg.WorkspaceID, arg.ExecutionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkspaceID,
			&i.AggregateType,
			&i.AggregateID,
			&i.ExecutionID,
			&i.Category,
			&i.EventName,
			&i.CorrelationID,
			&i.Payload,
			&i.Metadata,
			&i.PublishedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
