// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
       last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
FROM api_keys
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Prefix,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
       last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
FROM api_keys
WHERE prefix = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Prefix,
		&i.LastUsedIp,
		&i.LastUsedUserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, status, created_at, updated_at, deleted_at
FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByName = `-- name: GetOrganizationByName :one
SELECT id, name, status, created_at, updated_at, deleted_at
FROM organizations
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByName(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByName, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, organization_id, email, full_name, is_active, password_hash,
       email_verified_at, password_changed_at, last_login_at, status,
       created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, organization_id, email, full_name, is_active, password_hash,
       email_verified_at, password_changed_at, last_login_at, status,
       created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, organization_id, name, environment, status, created_at, updated_at, deleted_at
FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Environment,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorkspaceUser = `-- name: GetWorkspaceUser :one
SELECT workspace_id, user_id, role, created_at
FROM workspace_users
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceUser(ctx context.Context, arg GetWorkspaceUserParams) (WorkspaceUser, error) {
	row := q.db.QueryRow(ctx, getWorkspaceUser, arg.WorkspaceID, arg.UserID)
	var i WorkspaceUser
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (
  id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
  last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13
)
`

type InsertAPIKeyParams struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	Name              string             `json:"name"`
	KeyHash           string             `json:"key_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	Prefix            string             `json:"prefix"`
	LastUsedIp        *netip.Addr        `json:"last_used_ip"`
	LastUsedUserAgent *string            `json:"last_used_user_agent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.KeyHash,
		arg.LastUsedAt,
		arg.ExpiresAt,
		arg.Status,
		arg.Prefix,
		arg.LastUsedIp,
		arg.LastUsedUserAgent,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertOrganization = `-- name: InsertOrganization :exec
INSERT INTO organizations (id, name, status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrganizationParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error {
	_, err := q.db.Exec(ctx, insertOrganization,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
  id, organization_id, email, full_name, is_active, password_hash,
  email_verified_at, password_changed_at, last_login_at, status,
  created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10,
  $11, $12, $13
)
`

type InsertUserParams struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	PasswordHash      string             `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.FullName,
		arg.IsActive,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.PasswordChangedAt,
		arg.LastLoginAt,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspaces (id, organization_id, name, environment, status, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWorkspaceParams struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Environment    string             `json:"environment"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.Exec(ctx, insertWorkspace,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Environment,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertWorkspaceUser = `-- name: InsertWorkspaceUser :exec
INSERT INTO workspace_users (workspace_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertWorkspaceUserParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertWorkspaceUser(ctx context.Context, arg InsertWorkspaceUserParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceUser,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const listAPIKeysByWorkspace = `-- name: ListAPIKeysByWorkspace :many
SELECT id, workspace_id, name, key_hash, last_used_at, expires_at, status, prefix,
       last_used_ip, last_used_user_agent, created_at, updated_at, deleted_at
FROM api_keys
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Prefix,
			&i.LastUsedIp,
			&i.LastUsedUserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceUsersByUser = `-- name: ListWorkspaceUsersByUser :many
SELECT workspace_id, user_id, role, created_at
FROM workspace_users
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaceUsersByUser(ctx context.Context, userID uuid.UUID) ([]WorkspaceUser, error) {
	rows, err := q.db.Query(ctx, listWorkspaceUsersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceUser{}
	for rows.Next() {
		var i WorkspaceUser
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceUsersByWorkspace = `-- name: ListWorkspaceUsersByWorkspace :many
SELECT workspace_id, user_id, role, created_at
FROM workspace_users
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspaceUsersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceUser, error) {
	rows, err := q.db.Query(ctx, listWorkspaceUsersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceUser{}
	for rows.Next() {
		var i WorkspaceUser
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByOrganization = `-- name: ListWorkspacesByOrganization :many
SELECT id, organization_id, name, environment, status, created_at, updated_at, deleted_at
FROM workspaces
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListWorkspacesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Environment,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $2,
    updated_at = $2
WHERE id = $1 AND deleted_at IS NULL
`

type TouchAPIKeyLastUsedParams struct {
	ID         uuid.UUID          `json:"id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys
SET name = $2,
    key_hash = $3,
    expires_at = $4,
    status = $5,
    prefix = $6,
    updated_at = $7,
    deleted_at = $8
WHERE id = $1
`

type UpdateAPIKeyParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Status    string             `json:"status"`
	Prefix    string             `json:"prefix"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyHash,
		arg.ExpiresAt,
		arg.Status,
		arg.Prefix,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = $2,
    status = $3,
    updated_at = $4,
    deleted_at = $5
WHERE id = $1
`

type UpdateOrganizationParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET full_name = $2,
    is_active = $3,
    password_hash = $4,
    last_login_at = $5,
    status = $6,
    updated_at = $7,
    deleted_at = $8
WHERE id = $1
`

type UpdateUserParams struct {
	ID           uuid.UUID          `json:"id"`
	FullName     string             `json:"full_name"`
	IsActive     bool               `json:"is_active"`
	PasswordHash string             `json:"password_hash"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	Status       string             `json:"status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.IsActive,
		arg.PasswordHash,
		arg.LastLoginAt,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces
SET name = $2,
    environment = $3,
    status = $4,
    updated_at = $5,
    deleted_at = $6
WHERE id = $1
`

type UpdateWorkspaceParams struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Environment string             `json:"environment"`
	Status      string             `json:"status"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.Exec(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Environment,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
