// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveCredentialByConnection = `-- name: GetActiveCredentialByConnection :one
SELECT id, connection_id, type, status, version, encrypted_secret,
       expires_at, rotated_at, created_at, updated_at, created_by
FROM credentials
WHERE connection_id = $1 AND status = 'active'
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetActiveCredentialByConnection(ctx context.Context, connectionID uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getActiveCredentialByConnection, connectionID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Type,
		&i.Status,
		&i.Version,
		&i.EncryptedSecret,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getConnectionByID = `-- name: GetConnectionByID :one
SELECT id, active_credential_id, workspace_id, connector_id, name, is_default,
       description, environment, status, config, retry_policy, timeout_seconds,
       created_at, updated_at, deleted_at
FROM connections
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetConnectionByID(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionByID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.ActiveCredentialID,
		&i.WorkspaceID,
		&i.ConnectorID,
		&i.Name,
		&i.IsDefault,
		&i.Description,
		&i.Environment,
		&i.Status,
		&i.Config,
		&i.RetryPolicy,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConnectorByCode = `-- name: GetConnectorByCode :one
SELECT id, code, name, vendor, category, version, status,
       description, homepage, documentation_url, created_at, updated_at, deleted_at
FROM connectors
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetConnectorByCode(ctx context.Context, code string) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByCode, code)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Vendor,
		&i.Category,
		&i.Version,
		&i.Status,
		&i.Description,
		&i.Homepage,
		&i.DocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConnectorByID = `-- name: GetConnectorByID :one
SELECT id, code, name, vendor, category, version, status,
       description, homepage, documentation_url, created_at, updated_at, deleted_at
FROM connectors
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByID, id)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Vendor,
		&i.Category,
		&i.Version,
		&i.Status,
		&i.Description,
		&i.Homepage,
		&i.DocumentationUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, connection_id, type, status, version, encrypted_secret,
       expires_at, rotated_at, created_at, updated_at, created_by
FROM credentials
WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Type,
		&i.Status,
		&i.Version,
		&i.EncryptedSecret,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :exec
INSERT INTO connections (
  id, active_credential_id, workspace_id, connector_id, name, is_default,
  description, environment, status, config, retry_policy, timeout_seconds,
  created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15
)
`

type InsertConnectionParams struct {
	ID                 uuid.UUID          `json:"id"`
	ActiveCredentialID pgtype.UUID        `json:"active_credential_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ConnectorID        uuid.UUID          `json:"connector_id"`
	Name               string             `json:"name"`
	IsDefault          bool               `json:"is_default"`
	Description        *string            `json:"description"`
	Environment        string             `json:"environment"`
	Status             string             `json:"status"`
	Config             []byte             `json:"config"`
	RetryPolicy        []byte             `json:"retry_policy"`
	TimeoutSeconds     int32              `json:"timeout_seconds"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) error {
	_, err := q.db.Exec(ctx, insertConnection,
		arg.ID,
		arg.ActiveCredentialID,
		arg.WorkspaceID,
		arg.ConnectorID,
		arg.Name,
		arg.IsDefault,
		arg.Description,
		arg.Environment,
		arg.Status,
		arg.Config,
		arg.RetryPolicy,
		arg.TimeoutSeconds,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertConnector = `-- name: InsertConnector :exec
INSERT INTO connectors (
  id, code, name, vendor, category, version, status,
  description, homepage, documentation_url, created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13
)
`

type InsertConnectorParams struct {
	ID               uuid.UUID          `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Vendor           string             `json:"vendor"`
	Category         string             `json:"category"`
	Version          string             `json:"version"`
	Status           string             `json:"status"`
	Description      *string            `json:"description"`
	Homepage         *string            `json:"homepage"`
	DocumentationUrl *string            `json:"documentation_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertConnector(ctx context.Context, arg InsertConnectorParams) error {
	_, err := q.db.Exec(ctx, insertConnector,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Vendor,
		arg.Category,
		arg.Version,
		arg.Status,
		arg.Description,
		arg.Homepage,
		arg.DocumentationUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertConnectorCapability = `-- name: InsertConnectorCapability :exec
INSERT INTO connector_capabilities (
  id, connector_id, capability_code, display_name, status, is_async, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertConnectorCapabilityParams struct {
	ID             uuid.UUID          `json:"id"`
	ConnectorID    uuid.UUID          `json:"connector_id"`
	CapabilityCode string             `json:"capability_code"`
	DisplayName    string             `json:"display_name"`
	Status         string             `json:"status"`
	IsAsync        bool               `json:"is_async"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertConnectorCapability(ctx context.Context, arg InsertConnectorCapabilityParams) error {
	_, err := q.db.Exec(ctx, insertConnectorCapability,
		arg.ID,
		arg.ConnectorID,
		arg.CapabilityCode,
		arg.DisplayName,
		arg.Status,
		arg.IsAsync,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (
  id, connection_id, type, status, version, encrypted_secret,
  expires_at, rotated_at, created_at, updated_at, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11
)
`

type InsertCredentialParams struct {
	ID              uuid.UUID          `json:"id"`
	ConnectionID    uuid.UUID          `json:"connection_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	Version         int32              `json:"version"`
	EncryptedSecret []byte             `json:"encrypted_secret"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RotatedAt       pgtype.Timestamptz `json:"rotated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential,
		arg.ID,
		arg.ConnectionID,
		arg.Type,
		arg.Status,
		arg.Version,
		arg.EncryptedSecret,
		arg.ExpiresAt,
		arg.RotatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedBy,
	)
	return err
}

const listCapabilitiesByConnector = `-- name: ListCapabilitiesByConnector :many
SELECT id, connector_id, capability_code, display_name, status, is_async, created_at, updated_at
FROM connector_capabilities
WHERE connector_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCapabilitiesByConnector(ctx context.Context, connectorID uuid.UUID) ([]ConnectorCapability, error) {
	rows, err := q.db.Query(ctx, listCapabilitiesByConnector, connectorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorCapability{}
	for rows.Next() {
		var i ConnectorCapability
		if err := rows.Scan(
			&i.ID,
			&i.ConnectorID,
			&i.CapabilityCode,
			&i.DisplayName,
			&i.Status,
			&i.IsAsync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsByWorkspace = `-- name: ListConnectionsByWorkspace :many
SELECT id, active_credential_id, workspace_id, connector_id, name, is_default,
       description, environment, status, config, retry_policy, timeout_seconds,
       created_at, updated_at, deleted_at
FROM connections
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListConnectionsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.ActiveCredentialID,
			&i.WorkspaceID,
			&i.ConnectorID,
			&i.Name,
			&i.IsDefault,
			&i.Description,
			&i.Environment,
			&i.Status,
			&i.Config,
			&i.RetryPolicy,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectors = `-- name: ListConnectors :many
SELECT id, code, name, vendor, category, version, status,
       description, homepage, documentation_url, created_at, updated_at, deleted_at
FROM connectors
WHERE deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListConnectors(ctx context.Context) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connector{}
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Vendor,
			&i.Category,
			&i.Version,
			&i.Status,
			&i.Description,
			&i.Homepage,
			&i.DocumentationUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByConnection = `-- name: ListCredentialsByConnection :many
SELECT id, connection_id, type, status, version, encrypted_secret,
       expires_at, rotated_at, created_at, updated_at, created_by
FROM credentials
WHERE connection_id = $1
ORDER BY version DESC
`

func (q *Queries) ListCredentialsByConnection(ctx context.Context, connectionID uuid.UUID) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Type,
			&i.Status,
			&i.Version,
			&i.EncryptedSecret,
			&i.ExpiresAt,
			&i.RotatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :exec
UPDATE connections
SET active_credential_id = $2,
    name = $3,
    description = $4,
    status = $5,
    config = $6,
    retry_policy = $7,
    timeout_seconds = $8,
    updated_at = $9,
    deleted_at = $10
WHERE id = $1
`

type UpdateConnectionParams struct {
	ID                 uuid.UUID          `json:"id"`
	ActiveCredentialID pgtype.UUID        `json:"active_credential_id"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	Status             string             `json:"status"`
	Config             []byte             `json:"config"`
	RetryPolicy        []byte             `json:"retry_policy"`
	TimeoutSeconds     int32              `json:"timeout_seconds"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) error {
	_, err := q.db.Exec(ctx, updateConnection,
		arg.ID,
		arg.ActiveCredentialID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Config,
		arg.RetryPolicy,
		arg.TimeoutSeconds,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateConnector = `-- name: UpdateConnector :exec
UPDATE connectors
SET status = $2,
    updated_at = $3,
    deleted_at = $4
WHERE id = $1
`

type UpdateConnectorParams struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateConnector(ctx context.Context, arg UpdateConnectorParams) error {
	_, err := q.db.Exec(ctx, updateConnector,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials
SET status = $2,
    rotated_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateCredentialParams struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	RotatedAt pgtype.Timestamptz `json:"rotated_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential,
		arg.ID,
		arg.Status,
		arg.RotatedAt,
		arg.UpdatedAt,
	)
	return err
}
