// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                uuid.UUID          `json:"id"`
	WorkspaceID       uuid.UUID          `json:"workspace_id"`
	Name              string             `json:"name"`
	KeyHash           string             `json:"key_hash"`
	LastUsedAt        pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	Prefix            string             `json:"prefix"`
	LastUsedIp        *netip.Addr        `json:"last_used_ip"`
	LastUsedUserAgent *string            `json:"last_used_user_agent"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Connection struct {
	ID                 uuid.UUID          `json:"id"`
	ActiveCredentialID pgtype.UUID        `json:"active_credential_id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	ConnectorID        uuid.UUID          `json:"connector_id"`
	Name               string             `json:"name"`
	IsDefault          bool               `json:"is_default"`
	Description        *string            `json:"description"`
	Environment        string             `json:"environment"`
	Status             string             `json:"status"`
	Config             []byte             `json:"config"`
	RetryPolicy        []byte             `json:"retry_policy"`
	TimeoutSeconds     int32              `json:"timeout_seconds"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Connector struct {
	ID               uuid.UUID          `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	Vendor           string             `json:"vendor"`
	Category         string             `json:"category"`
	Version          string             `json:"version"`
	Status           string             `json:"status"`
	Description      *string            `json:"description"`
	Homepage         *string            `json:"homepage"`
	DocumentationUrl *string            `json:"documentation_url"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ConnectorCapability struct {
	ID             uuid.UUID          `json:"id"`
	ConnectorID    uuid.UUID          `json:"connector_id"`
	CapabilityCode string             `json:"capability_code"`
	DisplayName    string             `json:"display_name"`
	Status         string             `json:"status"`
	IsAsync        bool               `json:"is_async"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Credential struct {
	ID              uuid.UUID          `json:"id"`
	ConnectionID    uuid.UUID          `json:"connection_id"`
	Type            string             `json:"type"`
	Status          string             `json:"status"`
	Version         int32              `json:"version"`
	EncryptedSecret []byte             `json:"encrypted_secret"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RotatedAt       pgtype.Timestamptz `json:"rotated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	OrganizationID    uuid.UUID          `json:"organization_id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	IsActive          bool               `json:"is_active"`
	PasswordHash      string             `json:"password_hash"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Workspace struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	Name           string             `json:"name"`
	Environment    string             `json:"environment"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceUser struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
