// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceUser(ctx context.Context, arg GetWorkspaceUserParams) (WorkspaceUser, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error
	InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error
	InsertWorkspaceUser(ctx context.Context, arg InsertWorkspaceUserParams) error
	ListAPIKeysByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error)
	ListWorkspaceUsersByUser(ctx context.Context, userID uuid.UUID) ([]WorkspaceUser, error)
	ListWorkspaceUsersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceUser, error)
	ListWorkspacesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Workspace, error)
	Ping(ctx context.Context) (int32, error)
	TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error
}

var _ Querier = (*Queries)(nil)
