// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetActiveCredentialByConnection(ctx context.Context, connectionID uuid.UUID) (Credential, error)
	GetConnectionByID(ctx context.Context, id uuid.UUID) (Connection, error)
	GetConnectorByCode(ctx context.Context, code string) (Connector, error)
	GetConnectorByID(ctx context.Context, id uuid.UUID) (Connector, error)
	GetCredentialByID(ctx context.Context, id uuid.UUID) (Credential, error)
	GetExecutionByID(ctx context.Context, id uuid.UUID) (Execution, error)
	GetExecutionByIntentID(ctx context.Context, intentID uuid.UUID) (Execution, error)
	GetIdempotencyKeyByOrgWorkspaceKey(ctx context.Context, arg GetIdempotencyKeyByOrgWorkspaceKeyParams) (IdempotencyKey, error)
	GetIntentByID(ctx context.Context, id uuid.UUID) (Intent, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetSyncRouteByID(ctx context.Context, id uuid.UUID) (SyncRoute, error)
	GetSyncRouteWatermark(ctx context.Context, arg GetSyncRouteWatermarkParams) (SyncRouteWatermark, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceUser(ctx context.Context, arg GetWorkspaceUserParams) (WorkspaceUser, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertConnection(ctx context.Context, arg InsertConnectionParams) error
	InsertConnector(ctx context.Context, arg InsertConnectorParams) error
	InsertConnectorCapability(ctx context.Context, arg InsertConnectorCapabilityParams) error
	InsertCredential(ctx context.Context, arg InsertCredentialParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertExecution(ctx context.Context, arg InsertExecutionParams) error
	InsertExecutionSnapshot(ctx context.Context, arg InsertExecutionSnapshotParams) error
	InsertExecutionStep(ctx context.Context, arg InsertExecutionStepParams) error
	InsertExecutionTimeline(ctx context.Context, arg InsertExecutionTimelineParams) error
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	InsertIntent(ctx context.Context, arg InsertIntentParams) error
	InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error
	InsertSyncRoute(ctx context.Context, arg InsertSyncRouteParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error
	InsertWorkspaceUser(ctx context.Context, arg InsertWorkspaceUserParams) error
	ListAPIKeysByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error)
	ListCapabilitiesByConnector(ctx context.Context, connectorID uuid.UUID) ([]ConnectorCapability, error)
	ListConnectionsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Connection, error)
	ListConnectors(ctx context.Context) ([]Connector, error)
	ListCredentialsByConnection(ctx context.Context, connectionID uuid.UUID) ([]Credential, error)
	ListEnabledSchedulableSyncRoutes(ctx context.Context) ([]SyncRoute, error)
	ListEventsByWorkspace(ctx context.Context, arg ListEventsByWorkspaceParams) ([]Event, error)
	ListEventsByWorkspaceAndExecution(ctx context.Context, arg ListEventsByWorkspaceAndExecutionParams) ([]Event, error)
	ListExecutionSnapshotsByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionSnapshot, error)
	ListExecutionStepsByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionStep, error)
	ListExecutionTimelinesByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionTimeline, error)
	ListExecutionsByIntentID(ctx context.Context, intentID uuid.UUID) ([]Execution, error)
	ListSyncRouteWatermarks(ctx context.Context, syncRouteID uuid.UUID) ([]SyncRouteWatermark, error)
	ListSyncRoutesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]SyncRoute, error)
	ListWorkspaceUsersByUser(ctx context.Context, userID uuid.UUID) ([]WorkspaceUser, error)
	ListWorkspaceUsersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceUser, error)
	ListWorkspacesByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Workspace, error)
	Ping(ctx context.Context) (int32, error)
	TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error
	UpdateConnection(ctx context.Context, arg UpdateConnectionParams) error
	UpdateConnector(ctx context.Context, arg UpdateConnectorParams) error
	UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error
	UpdateExecution(ctx context.Context, arg UpdateExecutionParams) error
	UpdateExecutionStep(ctx context.Context, arg UpdateExecutionStepParams) error
	UpdateIntent(ctx context.Context, arg UpdateIntentParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdateSyncRoute(ctx context.Context, arg UpdateSyncRouteParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error
	UpsertSyncRouteWatermark(ctx context.Context, arg UpsertSyncRouteWatermarkParams) error
}

var _ Querier = (*Queries)(nil)
