// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_routes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncRouteByID = `-- name: GetSyncRouteByID :one
SELECT id, workspace_id, source_connection_id, name, status, trigger_type,
       resource_types, schedule, filter, idempotency_rule, activities, reverse, retry_policy,
       webhook_secret, created_at, updated_at, deleted_at
FROM sync_routes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSyncRouteByID(ctx context.Context, id uuid.UUID) (SyncRoute, error) {
	row := q.db.QueryRow(ctx, getSyncRouteByID, id)
	var i SyncRoute
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceConnectionID,
		&i.Name,
		&i.Status,
		&i.TriggerType,
		&i.ResourceTypes,
		&i.Schedule,
		&i.Filter,
		&i.IdempotencyRule,
		&i.Activities,
		&i.Reverse,
		&i.RetryPolicy,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSyncRouteWatermark = `-- name: GetSyncRouteWatermark :one
SELECT sync_route_id, resource_type, cursor, updated_at
FROM sync_route_watermarks
WHERE sync_route_id = $1 AND resource_type = $2
`

type GetSyncRouteWatermarkParams struct {
	SyncRouteID  uuid.UUID `json:"sync_route_id"`
	ResourceType string    `json:"resource_type"`
}

func (q *Queries) GetSyncRouteWatermark(ctx context.Context, arg GetSyncRouteWatermarkParams) (SyncRouteWatermark, error) {
	row := q.db.QueryRow(ctx, getSyncRouteWatermark, arg.SyncRouteID, arg.ResourceType)
	var i SyncRouteWatermark
	err := row.Scan(
		&i.SyncRouteID,
		&i.ResourceType,
		&i.Cursor,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSyncRoute = `-- name: InsertSyncRoute :exec
INSERT INTO sync_routes (
  id, workspace_id, source_connection_id, name, status, trigger_type,
  resource_types, schedule, filter, idempotency_rule, activities, reverse, retry_policy,
  webhook_secret, created_at, updated_at, deleted_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12, $13,
  $14, $15, $16, $17
)
`

type InsertSyncRouteParams struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	SourceConnectionID uuid.UUID          `json:"source_connection_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	TriggerType        string             `json:"trigger_type"`
	ResourceTypes      []byte             `json:"resource_types"`
	Schedule           []byte             `json:"schedule"`
	Filter             []byte             `json:"filter"`
	IdempotencyRule    []byte             `json:"idempotency_rule"`
	Activities         []byte             `json:"activities"`
	Reverse            []byte             `json:"reverse"`
	RetryPolicy        []byte             `json:"retry_policy"`
	WebhookSecret      []byte             `json:"webhook_secret"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) InsertSyncRoute(ctx context.Context, arg InsertSyncRouteParams) error {
	_, err := q.db.Exec(ctx, insertSyncRoute,
		arg.ID,
		arg.WorkspaceID,
		arg.SourceConnectionID,
		arg.Name,
		arg.Status,
		arg.TriggerType,
		arg.ResourceTypes,
		arg.Schedule,
		arg.Filter,
		arg.IdempotencyRule,
		arg.Activities,
		arg.Reverse,
		arg.RetryPolicy,
		arg.WebhookSecret,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const listSyncRouteWatermarks = `-- name: ListSyncRouteWatermarks :many
SELECT sync_route_id, resource_type, cursor, updated_at
FROM sync_route_watermarks
WHERE sync_route_id = $1
ORDER BY resource_type ASC
`

func (q *Queries) ListSyncRouteWatermarks(ctx context.Context, syncRouteID uuid.UUID) ([]SyncRouteWatermark, error) {
	rows, err := q.db.Query(ctx, listSyncRouteWatermarks, syncRouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRouteWatermark{}
	for rows.Next() {
		var i SyncRouteWatermark
		if err := rows.Scan(
			&i.SyncRouteID,
			&i.ResourceType,
			&i.Cursor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRoutesByWorkspace = `-- name: ListSyncRoutesByWorkspace :many
SELECT id, workspace_id, source_connection_id, name, status, trigger_type,
       resource_types, schedule, filter, idempotency_rule, activities, reverse, retry_policy,
       webhook_secret, created_at, updated_at, deleted_at
FROM sync_routes
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListSyncRoutesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]SyncRoute, error) {
	rows, err := q.db.Query(ctx, listSyncRoutesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRoute{}
	for rows.Next() {
		var i SyncRoute
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceConnectionID,
			&i.Name,
			&i.Status,
			&i.TriggerType,
			&i.ResourceTypes,
			&i.Schedule,
			&i.Filter,
			&i.IdempotencyRule,
			&i.Activities,
			&i.Reverse,
			&i.RetryPolicy,
			&i.WebhookSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncRoute = `-- name: UpdateSyncRoute :exec
UPDATE sync_routes
SET source_connection_id = $2,
    name = $3,
    status = $4,
    trigger_type = $5,
    resource_types = $6,
    schedule = $7,
    filter = $8,
    idempotency_rule = $9,
    activities = $10,
    reverse = $11,
    retry_policy = $12,
    webhook_secret = $13,
    updated_at = $14,
    deleted_at = $15
WHERE id = $1
`

type UpdateSyncRouteParams struct {
	ID                 uuid.UUID          `json:"id"`
	SourceConnectionID uuid.UUID          `json:"source_connection_id"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	TriggerType        string             `json:"trigger_type"`
	ResourceTypes      []byte             `json:"resource_types"`
	Schedule           []byte             `json:"schedule"`
	Filter             []byte             `json:"filter"`
	IdempotencyRule    []byte             `json:"idempotency_rule"`
	Activities         []byte             `json:"activities"`
	Reverse            []byte             `json:"reverse"`
	RetryPolicy        []byte             `json:"retry_policy"`
	WebhookSecret      []byte             `json:"webhook_secret"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateSyncRoute(ctx context.Context, arg UpdateSyncRouteParams) error {
	_, err := q.db.Exec(ctx, updateSyncRoute,
		arg.ID,
		arg.SourceConnectionID,
		arg.Name,
		arg.Status,
		arg.TriggerType,
		arg.ResourceTypes,
		arg.Schedule,
		arg.Filter,
		arg.IdempotencyRule,
		arg.Activities,
		arg.Reverse,
		arg.RetryPolicy,
		arg.WebhookSecret,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertSyncRouteWatermark = `-- name: UpsertSyncRouteWatermark :exec
INSERT INTO sync_route_watermarks (sync_route_id, resource_type, cursor, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sync_route_id, resource_type) DO UPDATE
SET cursor = EXCLUDED.cursor,
    updated_at = EXCLUDED.updated_at
`

type UpsertSyncRouteWatermarkParams struct {
	SyncRouteID  uuid.UUID          `json:"sync_route_id"`
	ResourceType string             `json:"resource_type"`
	Cursor       []byte             `json:"cursor"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertSyncRouteWatermark(ctx context.Context, arg UpsertSyncRouteWatermarkParams) error {
	_, err := q.db.Exec(ctx, upsertSyncRouteWatermark,
		arg.SyncRouteID,
		arg.ResourceType,
		arg.Cursor,
		arg.UpdatedAt,
	)
	return err
}
