// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int32     `json:"id"`
	Uuid     uuid.UUID `json:"uuid"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	FullName string    `json:"full_name"`
	// Age must be between 1 and 150
	Age *int32 `json:"age"`
	// 1: Active, 2: Inactive, 3: Banned
	Status int32 `json:"status"`
	// 1: Admin, 2: Moderator, 3: Member
	Level int32 `json:"level"`
	// Soft delete timestamp
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
}
