// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListUsersWCreatedAtAsc(ctx context.Context, arg ListUsersWCreatedAtAscParams) ([]User, error)
	ListUsersWCreatedAtDesc(ctx context.Context, arg ListUsersWCreatedAtDescParams) ([]User, error)
	ListUsersWUserIdAsc(ctx context.Context, arg ListUsersWUserIdAscParams) ([]User, error)
	ListUsersWUserIdDesc(ctx context.Context, arg ListUsersWUserIdDescParams) ([]User, error)
	RestoreUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	TrashUser(ctx context.Context, argUuid uuid.UUID) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
