// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(1) FROM users
WHERE (
	$1::bool IS NULL
	OR ($1::bool = TRUE AND deleted_at IS NOT NULL)
	OR ($1::bool = FALSE AND deleted_at IS NULL)
)
AND (
	$2::TEXT IS NULL
	OR $2::TEXT = ''
	OR email ILIKE '%' || $2 || '%'
	OR full_name ILIKE '%' || $2 || '%'
)
`

type CountUsersParams struct {
	Deleted *bool   `json:"deleted"`
	Search  *string `json:"search"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Deleted, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(
	email, password, full_name, age, status, level
) VALUES (
	$1, $2, $3, $4, $5, $6
) RETURNING id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	FullName string `json:"full_name"`
	Age      *int32 `json:"age"`
	Status   int32  `json:"status"`
	Level    int32  `json:"level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FullName,
		arg.Age,
		arg.Status,
		arg.Level,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at FROM users
WHERE uuid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersWCreatedAtAsc = `-- name: ListUsersWCreatedAtAsc :many
SELECT id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at FROM users
WHERE deleted_at IS NULL
AND (
	$3::TEXT IS NULL
	OR $3::TEXT = ''
	OR email ILIKE '%' || $3 || '%'
	OR full_name ILIKE '%' || $3 || '%'
)
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListUsersWCreatedAtAscParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

func (q *Queries) ListUsersWCreatedAtAsc(ctx context.Context, arg ListUsersWCreatedAtAscParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersWCreatedAtAsc, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Email,
			&i.Password,
			&i.FullName,
			&i.Age,
			&i.Status,
			&i.Level,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWCreatedAtDesc = `-- name: ListUsersWCreatedAtDesc :many
SELECT id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at FROM users
WHERE deleted_at IS NULL
AND (
	$3::TEXT IS NULL
	OR $3::TEXT = ''
	OR email ILIKE '%' || $3 || '%'
	OR full_name ILIKE '%' || $3 || '%'
)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersWCreatedAtDescParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

func (q *Queries) ListUsersWCreatedAtDesc(ctx context.Context, arg ListUsersWCreatedAtDescParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersWCreatedAtDesc, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Email,
			&i.Password,
			&i.FullName,
			&i.Age,
			&i.Status,
			&i.Level,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWUserIdAsc = `-- name: ListUsersWUserIdAsc :many
SELECT id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at FROM users
WHERE deleted_at IS NULL
AND (
	$3::TEXT IS NULL
	OR $3::TEXT = ''
	OR email ILIKE '%' || $3 || '%'
	OR full_name ILIKE '%' || $3 || '%'
)
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListUsersWUserIdAscParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

func (q *Queries) ListUsersWUserIdAsc(ctx context.Context, arg ListUsersWUserIdAscParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersWUserIdAsc, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Email,
			&i.Password,
			&i.FullName,
			&i.Age,
			&i.Status,
			&i.Level,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWUserIdDesc = `-- name: ListUsersWUserIdDesc :many
SELECT id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at FROM users
WHERE deleted_at IS NULL
AND (
	$3::TEXT IS NULL
	OR $3::TEXT = ''
	OR email ILIKE '%' || $3 || '%'
	OR full_name ILIKE '%' || $3 || '%'
)
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersWUserIdDescParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Search *string `json:"search"`
}

func (q *Queries) ListUsersWUserIdDesc(ctx context.Context, arg ListUsersWUserIdDescParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersWUserIdDesc, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Email,
			&i.Password,
			&i.FullName,
			&i.Age,
			&i.Status,
			&i.Level,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users SET
	deleted_at = NULL
WHERE uuid = $1::uuid AND deleted_at IS NOT NULL
RETURNING id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at
`

func (q *Queries) RestoreUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users SET
	deleted_at = NOW()
WHERE uuid = $1::uuid AND deleted_at IS NULL
RETURNING id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at
`

func (q *Queries) SoftDeleteUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trashUser = `-- name: TrashUser :one
DELETE FROM users
WHERE uuid = $1::uuid AND deleted_at IS NOT NULL
RETURNING id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at
`

func (q *Queries) TrashUser(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, trashUser, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users SET
	password = $1
WHERE uuid = $2 AND deleted_at IS NULL
RETURNING id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at
`

type UpdatePasswordParams struct {
	Password string    `json:"password"`
	Uuid     uuid.UUID `json:"uuid"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.Password, arg.Uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
	password = COALESCE($1, password),
	full_name = COALESCE($2, full_name),
	age = COALESCE($3, age),
	status = COALESCE($4, status),
	level = COALESCE($5, level)
WHERE uuid = $6 AND deleted_at IS NULL
RETURNING id, uuid, email, password, full_name, age, status, level, deleted_at, created_at, updated_at
`

type UpdateUserParams struct {
	Password *string   `json:"password"`
	FullName *string   `json:"full_name"`
	Age      *int32    `json:"age"`
	Status   *int32    `json:"status"`
	Level    *int32    `json:"level"`
	Uuid     uuid.UUID `json:"uuid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Password,
		arg.FullName,
		arg.Age,
		arg.Status,
		arg.Level,
		arg.Uuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Age,
		&i.Status,
		&i.Level,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
