-- Integration bounded context schema (docs/20-database-schema.dbml)
-- UUID primary keys are generated by the application (UUID v7).

DO $$ BEGIN
  CREATE TYPE connector_status AS ENUM ('registered', 'enabled', 'disabled', 'removed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE connector_category AS ENUM ('source', 'destination', 'bidirectional', 'utility');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE connector_capability_status AS ENUM ('enabled', 'disabled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE connection_status AS ENUM ('draft', 'verifying', 'active', 'verification_failed', 'disabled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE credential_type AS ENUM ('api_key', 'oauth2', 'bearer_token', 'basic_auth', 'jwt');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE credential_status AS ENUM ('active', 'expired', 'revoked');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS connectors (
  id UUID PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  vendor VARCHAR(255) NOT NULL,
  category connector_category NOT NULL,
  version VARCHAR(50) NOT NULL,
  status connector_status NOT NULL,
  description TEXT NULL,
  homepage VARCHAR(500) NULL,
  documentation_url VARCHAR(500) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ NULL,
  CONSTRAINT connectors_code_unique UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS connector_capabilities (
  id UUID PRIMARY KEY,
  connector_id UUID NOT NULL REFERENCES connectors (id),
  capability_code VARCHAR(150) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  status connector_capability_status NOT NULL,
  is_async BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT connector_capabilities_connector_code_unique UNIQUE (connector_id, capability_code)
);

CREATE TABLE IF NOT EXISTS connections (
  id UUID PRIMARY KEY,
  active_credential_id UUID NULL,
  workspace_id UUID NOT NULL REFERENCES workspaces (id),
  connector_id UUID NOT NULL REFERENCES connectors (id),
  name VARCHAR(255) NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT NULL,
  environment VARCHAR(50) NOT NULL,
  status connection_status NOT NULL,
  config JSONB NULL,
  retry_policy JSONB NULL,
  timeout_seconds INTEGER NOT NULL DEFAULT 30,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ NULL,
  CONSTRAINT connections_workspace_name_unique UNIQUE (workspace_id, name)
);

CREATE INDEX IF NOT EXISTS idx_connections_workspace_id ON connections (workspace_id);
CREATE INDEX IF NOT EXISTS idx_connections_connector_id ON connections (connector_id);
CREATE INDEX IF NOT EXISTS idx_connections_status ON connections (status);

CREATE TABLE IF NOT EXISTS credentials (
  id UUID PRIMARY KEY,
  connection_id UUID NOT NULL REFERENCES connections (id),
  type credential_type NOT NULL,
  status credential_status NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  encrypted_secret JSONB NOT NULL,
  expires_at TIMESTAMPTZ NULL,
  rotated_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_credentials_connection_id ON credentials (connection_id);
CREATE INDEX IF NOT EXISTS idx_credentials_status ON credentials (status);

ALTER TABLE connections
  ADD CONSTRAINT connections_active_credential_id_fkey
  FOREIGN KEY (active_credential_id) REFERENCES credentials (id);
