-- Orchestration bounded context schema (docs/20-database-schema.dbml)
-- UUID primary keys are generated by the application (UUID v7).
-- executions.intent_id is UNIQUE: one Execution per Intent in v1 (fan-out deferred).

DO $$ BEGIN
  CREATE TYPE intent_status AS ENUM ('submitted', 'accepted', 'rejected', 'expired');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE execution_status AS ENUM (
    'created', 'queued', 'running', 'succeeded', 'failed', 'cancelled', 'expired', 'dead_letter'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE execution_result AS ENUM ('success', 'failed', 'cancelled', 'expired', 'dead_letter');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE execution_step_type AS ENUM (
    'validate', 'transform_request', 'invoke_connector', 'transform_response', 'publish_event'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE execution_step_status AS ENUM ('pending', 'running', 'succeeded', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE snapshot_type AS ENUM (
    'canonical_request', 'provider_request', 'provider_response', 'canonical_response'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS intents (
  id UUID PRIMARY KEY,
  organization_id UUID NOT NULL REFERENCES organizations (id),
  workspace_id UUID NOT NULL REFERENCES workspaces (id),
  connection_id UUID NOT NULL REFERENCES connections (id),
  capability VARCHAR(150) NOT NULL,
  payload JSONB NULL,
  status intent_status NOT NULL,
  correlation_id VARCHAR(255) NULL,
  idempotency_key VARCHAR(255) NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT intents_idempotency_key_unique UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_intents_organization_id ON intents (organization_id);
CREATE INDEX IF NOT EXISTS idx_intents_workspace_id ON intents (workspace_id);
CREATE INDEX IF NOT EXISTS idx_intents_connection_id ON intents (connection_id);
CREATE INDEX IF NOT EXISTS idx_intents_capability ON intents (capability);
CREATE INDEX IF NOT EXISTS idx_intents_status ON intents (status);
CREATE INDEX IF NOT EXISTS idx_intents_correlation_id ON intents (correlation_id);
CREATE INDEX IF NOT EXISTS idx_intents_connection_submitted ON intents (connection_id, submitted_at);
CREATE INDEX IF NOT EXISTS idx_intents_organization_submitted ON intents (organization_id, submitted_at);

CREATE TABLE IF NOT EXISTS executions (
  id UUID PRIMARY KEY,
  intent_id UUID NOT NULL REFERENCES intents (id),
  status execution_status NOT NULL,
  result execution_result NULL,
  retry_attempt INTEGER NOT NULL DEFAULT 0,
  current_step_no INTEGER NOT NULL DEFAULT 0,
  context JSONB NULL,
  failure_reason TEXT NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT executions_intent_id_unique UNIQUE (intent_id)
);

CREATE INDEX IF NOT EXISTS idx_executions_status ON executions (status);
CREATE INDEX IF NOT EXISTS idx_executions_status_created ON executions (status, created_at);
CREATE INDEX IF NOT EXISTS idx_executions_started_at ON executions (started_at);
CREATE INDEX IF NOT EXISTS idx_executions_completed_at ON executions (completed_at);

CREATE TABLE IF NOT EXISTS execution_steps (
  id UUID PRIMARY KEY,
  execution_id UUID NOT NULL REFERENCES executions (id),
  step_no INTEGER NOT NULL,
  step_type execution_step_type NOT NULL,
  status execution_step_status NOT NULL,
  retry_attempt INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER NULL,
  error_message TEXT NULL,
  error_code VARCHAR(100) NULL,
  started_at TIMESTAMPTZ NULL,
  completed_at TIMESTAMPTZ NULL,
  CONSTRAINT execution_steps_execution_step_no_unique UNIQUE (execution_id, step_no)
);

CREATE INDEX IF NOT EXISTS idx_execution_steps_execution_id ON execution_steps (execution_id);
CREATE INDEX IF NOT EXISTS idx_execution_steps_status_started ON execution_steps (status, started_at);

CREATE TABLE IF NOT EXISTS execution_snapshots (
  id UUID PRIMARY KEY,
  execution_id UUID NOT NULL REFERENCES executions (id),
  step_id UUID NULL REFERENCES execution_steps (id),
  snapshot_type snapshot_type NOT NULL,
  snapshot JSONB NULL,
  content_type VARCHAR(100) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_execution_snapshots_execution_id ON execution_snapshots (execution_id);
CREATE INDEX IF NOT EXISTS idx_execution_snapshots_step_id ON execution_snapshots (step_id);
CREATE INDEX IF NOT EXISTS idx_execution_snapshots_type_created ON execution_snapshots (snapshot_type, created_at);

CREATE TABLE IF NOT EXISTS execution_timelines (
  id UUID PRIMARY KEY,
  execution_id UUID NOT NULL REFERENCES executions (id),
  event VARCHAR(150) NOT NULL,
  message TEXT NULL,
  metadata JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_execution_timelines_execution_id ON execution_timelines (execution_id);
CREATE INDEX IF NOT EXISTS idx_execution_timelines_created_at ON execution_timelines (created_at);
CREATE INDEX IF NOT EXISTS idx_execution_timelines_event_created ON execution_timelines (event, created_at);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  id UUID PRIMARY KEY,
  organization_id UUID NOT NULL REFERENCES organizations (id),
  workspace_id UUID NOT NULL REFERENCES workspaces (id),
  idempotency_key VARCHAR(255) NOT NULL,
  intent_id UUID NULL REFERENCES intents (id),
  expires_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT idempotency_keys_org_ws_key_unique UNIQUE (organization_id, workspace_id, idempotency_key)
);
