-- Events + Audit bounded context schema (docs/20-database-schema.dbml)
-- UUID primary keys are generated by the application (UUID v7).
-- Both tables are append-only / immutable: no UPDATE or DELETE queries are ever issued
-- against them (Repository ports only expose Save/Insert).

DO $$ BEGIN
  CREATE TYPE event_category AS ENUM ('runtime', 'business', 'system');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE aggregate_type AS ENUM (
    'organization', 'workspace', 'connector', 'connection', 'intent', 'execution'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE actor_type AS ENUM ('user', 'api_key', 'system');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY,

  organization_id UUID NULL REFERENCES organizations (id),
  workspace_id UUID NULL REFERENCES workspaces (id),

  aggregate_type aggregate_type NOT NULL,
  aggregate_id UUID NOT NULL,

  execution_id UUID NULL REFERENCES executions (id),
  category event_category NOT NULL,

  event_name VARCHAR(150) NOT NULL,
  correlation_id VARCHAR(255) NULL,

  payload JSONB NULL,
  metadata JSONB NULL,

  published_by VARCHAR(100) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_organization_id ON events (organization_id);
CREATE INDEX IF NOT EXISTS idx_events_workspace_id ON events (workspace_id);
CREATE INDEX IF NOT EXISTS idx_events_aggregate_type ON events (aggregate_type);
CREATE INDEX IF NOT EXISTS idx_events_aggregate_id ON events (aggregate_id);
CREATE INDEX IF NOT EXISTS idx_events_execution_id ON events (execution_id);
CREATE INDEX IF NOT EXISTS idx_events_category ON events (category);
CREATE INDEX IF NOT EXISTS idx_events_event_name ON events (event_name);
CREATE INDEX IF NOT EXISTS idx_events_correlation_id ON events (correlation_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events (created_at);
CREATE INDEX IF NOT EXISTS idx_events_aggregate_type_id ON events (aggregate_type, aggregate_id);
CREATE INDEX IF NOT EXISTS idx_events_category_created ON events (category, created_at);

CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY,
  organization_id UUID NULL REFERENCES organizations (id),
  workspace_id UUID NULL REFERENCES workspaces (id),
  actor_type actor_type NOT NULL,
  actor_id UUID NULL,
  action VARCHAR(150) NOT NULL,
  resource_type VARCHAR(100) NOT NULL,
  resource_id UUID NULL,
  request_id VARCHAR(255) NULL,
  correlation_id VARCHAR(255) NULL,
  ip INET NULL,
  user_agent TEXT NULL,
  metadata JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_organization_id ON audit_logs (organization_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_workspace_id ON audit_logs (workspace_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_type ON audit_logs (actor_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id ON audit_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type ON audit_logs (resource_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_id ON audit_logs (resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_request_id ON audit_logs (request_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_correlation_id ON audit_logs (correlation_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_type_id ON audit_logs (actor_type, actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type_id ON audit_logs (resource_type, resource_id);
