-- SyncRoute: Integration configuration (not a Runtime Aggregate).
-- docs/30-mvp-usecase-nhanh-misa.md §5.2; AGENTS.md SyncRoute clarification.
-- UUID primary keys are generated by the application (UUID v7).

DO $$ BEGIN
  CREATE TYPE sync_route_status AS ENUM ('draft', 'enabled', 'disabled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE sync_route_trigger AS ENUM ('webhook', 'schedule', 'both');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE aggregate_type ADD VALUE 'sync_route';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS sync_routes (
  id UUID PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES workspaces (id),
  source_connection_id UUID NOT NULL REFERENCES connections (id),

  name VARCHAR(255) NOT NULL,
  status sync_route_status NOT NULL,
  trigger_type sync_route_trigger NOT NULL,

  resource_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  schedule JSONB NULL,
  filter JSONB NULL,
  idempotency_rule JSONB NULL,
  activities JSONB NOT NULL DEFAULT '[]'::jsonb,
  reverse JSONB NULL,
  retry_policy JSONB NULL,

  -- Encrypted envelope (same shape as credentials.encrypted_secret). Never log / never echo plaintext.
  webhook_secret JSONB NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ NULL,

  CONSTRAINT sync_routes_workspace_name_unique UNIQUE (workspace_id, name)
);

CREATE INDEX IF NOT EXISTS idx_sync_routes_workspace_id ON sync_routes (workspace_id);
CREATE INDEX IF NOT EXISTS idx_sync_routes_source_connection_id ON sync_routes (source_connection_id);
CREATE INDEX IF NOT EXISTS idx_sync_routes_status ON sync_routes (status);

-- Poll watermark / cursor per SyncRoute + resource_type (docs/30 §7.2). Postgres is source of truth.
CREATE TABLE IF NOT EXISTS sync_route_watermarks (
  sync_route_id UUID NOT NULL REFERENCES sync_routes (id),
  resource_type VARCHAR(100) NOT NULL,
  cursor JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (sync_route_id, resource_type)
);

CREATE INDEX IF NOT EXISTS idx_sync_route_watermarks_updated_at ON sync_route_watermarks (updated_at);
