package domain

import "errors"

var (
	ErrInvalidCode           = errors.New("integration: invalid code")
	ErrInvalidName           = errors.New("integration: invalid name")
	ErrInvalidVendor         = errors.New("integration: invalid vendor")
	ErrInvalidCategory       = errors.New("integration: invalid category")
	ErrInvalidVersion        = errors.New("integration: invalid version")
	ErrInvalidEnvironment    = errors.New("integration: invalid environment")
	ErrInvalidCredentialType = errors.New("integration: invalid credential type")
	ErrInvalidTransition     = errors.New("integration: invalid status transition")
	ErrConnectorRemoved      = errors.New("integration: connector is removed")
	ErrConnectorNotUsable    = errors.New("integration: connector is not enabled")
	ErrCapabilityNotFound    = errors.New("integration: capability not found")
	ErrCredentialNotActive   = errors.New("integration: credential is not active")
	ErrConnectionNotActive   = errors.New("integration: connection is not active")
	ErrEmptySecret           = errors.New("integration: encrypted secret is required")
	ErrNotFound              = errors.New("integration: not found")
	ErrConflict              = errors.New("integration: conflict")

	ErrInvalidSyncRouteTrigger = errors.New("integration: invalid sync route trigger")
	ErrInvalidResourceTypes    = errors.New("integration: invalid resource_types")
	ErrInvalidActivityGroup    = errors.New("integration: invalid activity group")
	ErrInvalidActivityStep     = errors.New("integration: invalid activity step")
	ErrInvalidReverseConfig    = errors.New("integration: invalid reverse config")
	ErrInvalidSchedule         = errors.New("integration: schedule required for schedule trigger")
	ErrWebhookSecretRequired   = errors.New("integration: webhook secret required")
	ErrSyncRouteRemoved        = errors.New("integration: sync route is removed")
	ErrSyncRouteNotEditable    = errors.New("integration: enabled sync route cannot be edited; disable first")
	ErrSyncRouteNotEnabled     = errors.New("integration: sync route is not enabled")
	ErrWebhookNotConfigured    = errors.New("integration: sync route does not accept webhooks")
	ErrWebhookSecretMismatch   = errors.New("integration: webhook secret mismatch")
	ErrResourceTypeNotAllowed  = errors.New("integration: resource_type not allowed on sync route")
	ErrFilterRejected          = errors.New("integration: payload rejected by sync route filter")
	ErrInvalidFilter           = errors.New("integration: invalid filter")
)
